[package]
name = "hef-db"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hef-core = { path = "../core" }
sqlx = { workspace = true }
uuid = { version = "1.25", features = ["v7"] }
thiserror = "2"
tokio = { workspace = true, features = ["rt", "macros", "time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
